project:
  type: website

website:
  title: "Jordan and Zoe E155 Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: results.qmd
        text: Results
      - href: documentation.qmd
        text: Documentation
      - href: mcu.qmd
        text: MCU Design
      - href: fpga.qmd
        text: FGPA Design
      - href: appendices.qmd
        text: Appendices
      - href: team.qmd
        text: Team

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    smooth-scroll: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px
